### ISSUE TITLE
request: add ms graph api upload limit warning 

### ISSUE THREAD

**Issue by zabderra** [sascommunities/sas-microsoft-graph-api#1]
Hello,

It could be interesting to add a warning about the ms graph api upload limit warning:
https://learn.microsoft.com/en-us/answers/questions/1162685/can-we-used-more-than-4mb-file-upload-using-graph

Thank you in advance.
Regards
Abder

**Comment by cjdinger** [comment]
I've implemented the approach that supports large files with an upload session. It splits the source file into segments that can be uploaded in sequence, then iterates through these to get them uploaded to the target folder.
