### ISSUE TITLE
Log warnings in %downloadFile macro

### ISSUE THREAD

**Issue by mprikolota** [sascommunities/sas-microsoft-graph-api#2]
Hi Chris, many thanks for the macros - very usefull!

I was able to successfully download a file using the macro %downloadFile, but I'm getting some strange warnings about not resolved references which appear to be coming from PROC HTTP. Do you have any idea what might be wrong? Below you can see part of the log.

Many thanks,

Maksym

```
NOTE: Deleting WORK.__TMPLST (memtype=DATA).
NOTE: PROCEDURE DELETE used (Total process time):
real time 0.00 seconds
cpu time 0.00 seconds

WARNING: Apparent symbolic reference TRANSLATE not resolved.
WARNING: Apparent symbolic reference TRANSLATE not resolved.
WARNING: Apparent symbolic reference TEMPAUTH not resolved.
WARNING: Apparent symbolic reference APIVERSION not resolved.
WARNING: Apparent symbolic reference TRANSLATE not resolved.
WARNING: Apparent symbolic reference TRANSLATE not resolved.
WARNING: Apparent symbolic reference TEMPAUTH not resolved.
WARNING: Apparent symbolic reference APIVERSION not resolved.
NOTE: 200 OK
NOTE: PROCEDURE HTTP used (Total process time):
real time 0.28 seconds
cpu time 0.05 seconds
```

**Comment by cjdinger** [comment]
Hi @mprikolota - thanks for the feedback. The way the Download macro works is that it grabs "download URL" from the Microsoft 365 data properties about the file, and then simply GETs that URL using PROC HTTP. The URL (provided by the system) has a number of URL parameters that are set off with & characters, and the ampersand character has a special meaning in SAS for macro variables.

So the warning is innocuous in this case -- it's just SAS trying to resolve these "macro variables". I did play with trying to escape or use %nrstr() to prevent SAS from processing these, but didn't get it working the way it should. It does not affect how it works but it does clutter the log.

**Comment by mprikolota** [comment]
Thanks Chris for so quick reply!

**Comment by mprikolota** [comment]
BTW, there is a small bug in that macro:
![image](https://github.com/sascommunities/sas-microsoft-graph-api/assets/92910512/6f0b6240-9bf8-4f82-ae40-6440f1190125)

**Comment by cjdinger** [comment]
@mprikolota Thanks for the bug report. I've fixed that. I also addressed the warnings you noticed. AND I added more robust support for large files. That required quite a bit of scaffolding to first split the source file into segments that can be uploaded in sequence.
